# Site
repository: pokeylooted/Pokeylooted.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Pokeylooted
title: Developer
email: contact@exorbgn.net
website: pokey.is-a.dev

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: Pokeylooted
github_username:  Pokeylooted
discord_username: .pokeyy
stackoverflow_username: "26754392"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009-0006-0234-6031

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's pokey and I'm system administrator. As well as administrating systems I also have experience making software and web apps. I channel my own passion, and create projects as robust as efficient as I can till I get my own Jarvis. For me, every line of code is a opportunity to learn and improve.

  I am most skilled in: <mark>FastAPI</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Shard - A FOSS Clipping software
        link: github.com/pokeylooted/Shard
        # link_text: Project Website
        additional_links:
          - title:  pokeylooted/Shard
            icon: fab fa-github
            url: github.com/Pokeylooted/Shard
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning <mark>React</mark> and <mark>FastAPI</mark>, it has since then grown into a fullstack app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Automation & Security # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Reliable Automation
        sub_title: Consistent Performance
        caption: Efficiency through Automation
        quote: >
          "Automation ensures tasks are executed reliably and consistently."
        description: | # this will include new lines to allow paragraphs
          I believe in the power of automation to handle repetitive tasks with precision and reliability. By implementing automated processes, I ensure that tasks are performed consistently and efficiently, reducing the risk of errors and freeing up time for more strategic work. My focus is on creating robust automation solutions that deliver dependable results every time.

      - layout: left
        title: Vigilant Security
        sub_title: Prioritizing Safety
        caption: Serious Approach to Security
        quote: >
          "Every security issue is a priority and demands immediate attention."
        description: | # this will include new lines to allow paragraphs
          Security is a critical aspect of my work, and I take every issue seriously. I am dedicated to thoroughly assessing and addressing any vulnerabilities in my applications. By maintaining a proactive approach to security, I ensure that potential risks are managed effectively, safeguarding both the integrity of the systems and the trust of users.


  - title: Philosophy & Approach # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Learning by Doing
        caption: Motivation is Key
        sub_title: Passion-Driven Development
        quote: >
          Life is like programming—constant iteration, constant improvement.
        description: | # this will include new lines to allow paragraphs
          I believe the best way to master something is by diving right into it. Whether it's programming, system admin, or exploring new tech, I approach every challenge as an opportunity to build, break, and learn. 

          In my projects, I prioritize solutions that aren't just functional but efficient. Every line of code deserves a purpose, and I believe simplicity leads to the most powerful outcomes. 

          My work is driven by my inner passion—whether it's for tech, building the future one line of code at a time, or just embracing the mechanic mentality as Tony Stark would put it. I channel this enthusiasm into every project, striving to create tools that aren't just useful, but enjoyable! 

          I'm always looking to learn, improve, and adapt. Whether it's through personal projects or contributing to others, I see every experience as a chance to grow and maybe one day, I might have my own Iron Man suit.
    
      - layout: left
        title: Collaboration and Community
        sub_title: Building Together
        quote: >
          The strength of the team is each individual member. The strength of each member is the team.
        description: |
          I believe in the power of collaboration and community to achieve outstanding results. I see working together and sharing knowledge as key to driving innovation and growth. 

          Whether through team projects, open-source contributions, or engaging with the tech community, I'm committed to learning from others and contributing to collective success. Working together allows us to tackle complex problems and build solutions that are greater than the sum of their parts.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Aeronautics
      - Gaming
      - Skydiving
      - Learning too fly

      Me writing print(Hello World!):  
      ![Developing](/Pokeylooted.github.io/images/tony.jpg "Developing")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme


sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
